### ISSUE TITLE
How to use for uitableviewcell

### ISSUE THREAD

**Issue by dexcell** [edwellbrook/Themeable#3]
How do i theme uitableview cell?
Since this is repeating cell, it doesn't available in `apply` method
Thanks

**Comment by edwellbrook** [comment]
Hey! I've found making a simple subclass is the best way to do this.

Here's an example. Hope it helps: https://gist.github.com/edwellbrook/35bd45f4bede309d6680897dc2e00af1

Let me know if this solves your problem 😄

**Comment by dexcell** [comment]
Wow, thank you for your superfast response!
Thanks i've got it 😃 

Happy holidays 🎄

**Comment by dexcell** [comment]
Hi, for some of my cell, i need to show different colors depending on their property.
(for example. zebra table based on row % 2 == 0)

I managed to do it by calling the apply method manually, is this the best approach? (Since the apply function will be called twice?)

````
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell:OrderBookCell = tableView.dequeueReusableCell(withIdentifier: "OrderBookCell", for: indexPath) as! OrderBookCell
        
        let orderBookItem = self.orderBookItems[indexPath.row]
        cell.row = indexPath.row

       // Call apply manually
        cell.apply(theme: AppTheme.manager.activeTheme)

````

In subclassed UITableViewCell

````
func apply(theme: AppTheme) {
        if (self.row != nil) {
            if (self.row! % 2 == 0) {
                self.rateLabel.backgroundColor =  theme.cellEvenBackgroundColor
            } else {
                self.rateLabel.backgroundColor =  theme.cellOddBackgroundColor
            }
        }
    }
````

**Comment by edwellbrook** [comment]
It's fine to call `apply(theme:_)` multiple times 😄. The code you've provided should work with no problems.

I'm thinking a better solution here might be for me to also add a helper method to Themeable which would re-trigger the `apply(theme:_)` method. Would a something like `cell.reapplyTheme()` be useful to you?

**Comment by dexcell** [comment]
I see, i just want confirmation from you. Yeah, it works without any problem 👍  

````
I'm thinking a better solution here might be for me to also add a helper method to Themeable which would re-trigger the apply(theme:_) method. Would a something like cell.reapplyTheme() be useful to you?
````
I don't think it's necessary, let's keep it simple just like this 😄
